### ISSUE TITLE
Models?

### ISSUE THREAD

**Issue by araykhel-CS** [getalp/WSD-IWCS2017-Vialetal#1]
In your paper (which was very interesting!) you said your code is available here, but there is only a readme. :'(

**Comment by loic-vial** [comment]
Hello ! Thank you :) 

We are really sorry we forgot to update this repository. The sense embeddings models are too large to fit on Github so we uploaded them here: https://persyval-platform.univ-grenoble-alpes.fr/DS117/detaildataset

We also updated the readme of this repository.

Don't hesitate to contact us, our email addresses are in the paper :)
